### ISSUE TITLE
Suggestion: Automatically download the lexicon if it doesn't exist

### ISSUE THREAD

**Issue by HamedMP** [bjesus/swe#1]
Super cool project @bjesus! 🚀 

I found the setup can be easier. Especially the link provided  (https://folkets-lexikon.csc.kth.se/folkets/folkets_sv_en_public.xml) doesn't start downloading directly (in my browser at least). 

It was possible to `wget https://folkets-lexikon.csc.kth.se/folkets/folkets_sv_en_public.xml` to download the file and I think it'll make the script easier to use. 

On distribution suggestion, I would also recommend publishing it in [Homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew) or PyPI so it'll be easier to distribute and install. 

Good luck! 🌟

**Comment by HamedMP** [comment]
And oh, since the dictionary is "living" (updating over time), would be nice to update the file if it's been downloaded more than 1 month ago or something. (plus having flags to fetch the latest version).

**Comment by bjesus** [comment]
`swe` now features a full [Textual](https://textual.textualize.io/)-based TUI, is installable with `pipx install swe` and automatically downloads the required dictionary file if it doesn't exist.
